# Example config file

# Directories
datasets:
  -
    name: data1
    glob_pattern: '*.jsonl.gz'
    input_dir: data1/
    output_dir: output/data1/
    exclusion_dir: exclusions/data1/
    logging_dir: logs/data1/
  -
    name: data2
    glob_pattern: '*.jsonl.gz'
    input_dir: data2/
    output_dir: output/data2/
    exclusion_dir: exclusions/data2/
    logging_dir: logs/data2/

# Deduplication
sentence_deduplication:
  input_dir: output/
  glob_pattern: '**/*.parquet'
  dedup_dir: dedup/sent/
  exclusion_dir: exclusions/sent_deup
  output_dir: output/sent_dedup/
  logging_dir: logs/sent_dedup/

minhash_deduplication:
  input_dir: output/sent_dedup/
  glob_pattern: '**/*.parquet'
  dedup_dir: dedup/minhash/
  exclusion_dir: exclusions/minhash_deup
  output_dir: output/minhash_dedup/
  logging_dir: logs/minhash_dedup/
  n_buckets: 10   # <---- This should match with `executor.n_tasks`


# Executor
executor:
  n_workers: 5
  n_tasks: 10   # <---- This should match with `minhash_deduplication.n_buckets`
  debug: False


cluster:
  type: local # distributed
  scheduler_host: localhost
  scheduler_port: 8786
  # scheduler_file:
  n_workers: 5
